package com.manna.bible.data.bundled

import android.content.Context
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.Json
import java.io.FileNotFoundException
import java.io.IOException
import java.util.zip.GZIPInputStream
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Reads the bundled Bible assets under `assets/bibles/` produced by the
 * `:app:prepareBundledBibles` Gradle task.
 *
 * All I/O and JSON decoding happens on [Dispatchers.IO]. The reader is tolerant
 * of the assets being absent: the actual files are generated by CI before
 * assembling the release, so on a developer machine (or before the task has
 * run) they may not exist. In that case [manifest] returns `null` and the
 * seeder no-ops.
 *
 * The injected [Json] instance is configured to ignore unknown keys, so additive
 * schema changes from the generator won't break older parsers.
 */
@Singleton
class BundledBibleAssetReader @Inject constructor(
    @ApplicationContext private val context: Context,
    private val json: Json
) {

    /**
     * Reads and parses `assets/bibles/manifest.json`.
     *
     * Returns `null` when the manifest asset is not present (for example, before
     * the bundled-content Gradle task has run), allowing the seeder to skip
     * gracefully instead of crashing.
     */
    suspend fun manifest(): BundledManifest? = withContext(Dispatchers.IO) {
        try {
            val raw = context.assets
                .open("$BIBLES_DIR/$MANIFEST_FILE")
                .bufferedReader()
                .use { it.readText() }
            json.decodeFromString<BundledManifest>(raw)
        } catch (_: FileNotFoundException) {
            null
        } catch (_: IOException) {
            // assets.open throws a plain IOException when the asset is missing.
            null
        }
    }

    /**
     * Opens `assets/bibles/{assetFile}` (a gzipped JSON file), decompresses it,
     * and decodes the JSON into a [BundledBible].
     *
     * Unlike [manifest], a missing or unreadable content file here is a genuine
     * error (the manifest referenced it), so I/O failures propagate.
     */
    suspend fun read(assetFile: String): BundledBible = withContext(Dispatchers.IO) {
        val raw = context.assets
            .open("$BIBLES_DIR/$assetFile")
            .let(::GZIPInputStream)
            .bufferedReader()
            .use { it.readText() }
        json.decodeFromString<BundledBible>(raw)
    }

    private companion object {
        const val BIBLES_DIR = "bibles"
        const val MANIFEST_FILE = "manifest.json"
    }
}
